entry <- function(gene_or_element,
                  organism,
                  regulatory_context,
                  uorf_architecture,
                  known_effect_on_cds,
                  mechanism,
                  expected_riboseq_signature,
                  relevance_to_rdg_model,
                  evidence_type,
                  primary_citation,
                  url,
                  notes = "") {
  data.frame(
    gene_or_element = gene_or_element,
    organism = organism,
    regulatory_context = regulatory_context,
    uorf_architecture = uorf_architecture,
    known_effect_on_cds = known_effect_on_cds,
    mechanism = mechanism,
    expected_riboseq_signature = expected_riboseq_signature,
    relevance_to_rdg_model = relevance_to_rdg_model,
    evidence_type = evidence_type,
    primary_citation = primary_citation,
    url = url,
    notes = notes,
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}

known_uorf_effects <- do.call(rbind, list(
  entry(
    "Genome-wide human uORFs",
    "Human and mouse",
    "Basal transcript architecture",
    "uAUG/uORFs in about half of mammalian transcripts",
    "Usually lowers downstream protein output",
    "Scanning ribosomes initiate upstream, then dissociate, reinitiate inefficiently, trigger NMD, or stall before reaching the CDS.",
    "Leader ribosome footprints with lower CDS translation efficiency on average.",
    "Default prior: translated uORFs are more often repressors than activators, but mechanism must be gene-specific.",
    "Matched mRNA/protein analysis plus reporter validation",
    "Calvo et al., Proc Natl Acad Sci USA, 2009",
    "https://doi.org/10.1073/pnas.0810916106",
    "Use as a broad prior only; individual uORFs can be positive, neutral, or condition-dependent."
  ),
  entry(
    "Translated human uORF variants",
    "Human",
    "Population genetics and disease association",
    "Translated uORFs from ribosome profiling intersected with human variation",
    "Stop-creating or stop-strengthening variants can reduce downstream protein expression",
    "Premature or stronger uORF termination changes the probability of downstream reinitiation at the CDS.",
    "Variant-specific decrease in reporter/CDS output; constrained uORF start and stop positions.",
    "Good model for interpreting disease-associated 5-prime UTR variants that alter ribosome decision flow.",
    "Population genetics, biobank association, reporter validation",
    "Lee et al., Nature Communications, 2021",
    "https://pmc.ncbi.nlm.nih.gov/articles/PMC7943595/",
    "Useful for prioritizing human 5-prime UTR variants that alter uORF starts/stops."
  ),
  entry(
    "GCN4",
    "Saccharomyces cerevisiae",
    "Amino acid starvation; low ternary complex",
    "Four short uORFs; uORF1 is permissive/positive, downstream uORFs are inhibitory",
    "CDS down in rich medium; CDS up during amino acid starvation",
    "After uORF1 translation, 40S resumes scanning. High ternary complex causes reinitiation at inhibitory uORFs; low ternary complex delays reinitiation until the CDS.",
    "High uORF1 use; starvation shifts downstream initiation from inhibitory uORFs to GCN4 CDS.",
    "Canonical delayed-reinitiation decision graph benchmark.",
    "Start-codon mutagenesis, reporter assays, reinitiation genetics",
    "Mueller and Hinnebusch, Cell, 1986; Abastado et al., Mol Cell Biol, 1991",
    "https://pubmed.ncbi.nlm.nih.gov/3516411/",
    "Mechanistic ancestor of the ATF4-like ISR architecture."
  ),
  entry(
    "ATF4",
    "Mammal / human",
    "Integrated stress response; eIF2alpha phosphorylation",
    "Short positive uORF1 followed by an overlapping inhibitory uORF2",
    "CDS down without stress; CDS up during ISR stress",
    "uORF1 promotes rescanning; under low eIF2-GTP, ribosomes bypass inhibitory uORF2 and initiate at ATF4 CDS.",
    "Stress increases ATF4 CDS footprints while inhibitory overlapping uORF2 is relatively bypassed.",
    "Primary positive-control gene for clean-CDS masking and RDG branch inference.",
    "Reporter mutagenesis, polysome/ribosome logic, ISR perturbation",
    "Vattem and Wek, Proc Natl Acad Sci USA, 2004",
    "https://pubmed.ncbi.nlm.nih.gov/15277680/",
    "Because uORF2 overlaps the CDS, CDS coverage must exclude overlapping uORF bases for RDG inference."
  ),
  entry(
    "ATF5",
    "Mammal / human",
    "Amino acid limitation and other ISR-like stresses",
    "Alternative 5-prime UTRs; conserved uORF1/uORF2 architecture in 5-prime UTR alpha",
    "CDS preferentially translated during stress",
    "ATF4-like delayed reinitiation through conserved uORFs in the stress-responsive 5-prime leader.",
    "Stress should increase CDS translation relative to basal leader decisions.",
    "Candidate benchmark for ATF4-like genes not yet in the current dominant-state marker panel.",
    "Reporter constructs and stress induction",
    "Watatani et al., Journal of Biological Chemistry, 2008",
    "https://doi.org/10.1074/jbc.M707781200",
    "Include if future marker sets expand beyond ATF4/DDIT3/PPP1R15A."
  ),
  entry(
    "PPP1R15A / GADD34",
    "Mammal / human",
    "Integrated stress response feedback; eIF2alpha phosphorylation",
    "Two uORFs; downstream uORF is the main inhibitory barrier",
    "CDS low basally; CDS preferentially translated during ISR",
    "Stress-induced eIF2alpha phosphorylation promotes bypass of the inhibitory uORF and initiation at the GADD34 CDS.",
    "Stress increases PPP1R15A CDS translation; basal samples show stronger uORF barrier.",
    "Direct marker in the dominant ISR module and candidate feedback node in RDGs.",
    "5-prime UTR reporters, polysome profiling, uORF perturbation",
    "Lee et al., Journal of Biological Chemistry, 2009; Young et al., Journal of Biological Chemistry, 2015",
    "https://pmc.ncbi.nlm.nih.gov/articles/PMC2652341/",
    "The later Young et al. paper compares PPP1R15A/GADD34 and PPP1R15B/CReP uORF logic."
  ),
  entry(
    "PPP1R15B / CReP",
    "Mammal / human",
    "Constitutive eIF2alpha phosphatase targeting",
    "Two uORFs with a reinitiation-permissive downstream uORF",
    "CDS remains comparatively constitutive rather than strongly stress-induced",
    "The downstream uORF allows resumed scanning and reinitiation at the CReP CDS independent of eIF2alpha-P status.",
    "Leader and CDS footprints should remain less stress-switch-like than PPP1R15A.",
    "Useful negative/control example: similar family and uORF count but different decision outcome.",
    "Biochemical and genetic uORF comparison with GADD34",
    "Young et al., Journal of Biological Chemistry, 2015",
    "https://pmc.ncbi.nlm.nih.gov/articles/PMC4653682/",
    "Good reminder that uORF count alone is not enough; spacing and reinitiation competence matter."
  ),
  entry(
    "DDIT3 / CHOP",
    "Mammal / human",
    "ER stress, amino acid stress, ISR",
    "Conserved inhibitory uORF in the 5-prime leader",
    "CDS low basally; CDS induced during stress",
    "The uORF peptide stalls or impairs elongation/termination and blocks downstream initiation; stress promotes bypass of this barrier.",
    "Stress increases CHOP/DDIT3 CDS translation while uORF barrier is reduced; uORF deletion strongly increases CDS expression.",
    "Direct ISR marker and benchmark for peptide-dependent inhibitory uORFs.",
    "Reporter mutagenesis, peptide sequence tests, ISR stress assays",
    "Jousse et al., Nucleic Acids Research, 2001; Young et al., Journal of Biological Chemistry, 2016",
    "https://pubmed.ncbi.nlm.nih.gov/11691921/",
    "Human CHOP can also be derepressed by ENDOU-mediated cleavage of the inhibitory uORF transcript."
  ),
  entry(
    "EPO",
    "Human",
    "Hypoxia",
    "14-codon uORF in the EPO 5-prime leader",
    "CDS repressed in unstressed cells; hypoxia releases repression in some cells",
    "Hypoxia and eIF2alpha phosphorylation increase ribosome bypass of the uORF and translation of EPO CDS.",
    "Hypoxia-specific increase in CDS translation without requiring proportional mRNA increase.",
    "Hypoxia benchmark for uORF-regulated hormone output.",
    "Reporter assays and endogenous hypoxia response",
    "Barbosa and Romao, RNA, 2014",
    "https://pmc.ncbi.nlm.nih.gov/articles/PMC3988562/",
    "Relevant to hypoxia branches, but EPO is tissue-restricted and may not appear broadly in RiboCrypt samples."
  ),
  entry(
    "VEGFA",
    "Human",
    "Angiogenesis; hypoxia-associated translational control",
    "Small uORF embedded within an IRES in the long VEGFA 5-prime leader",
    "Negatively regulates expression of the VEGF121 isoform",
    "Cap-independent translation of the uORF within the IRES changes isoform-specific AUG/CUG initiation choices.",
    "Isoform-specific leader footprints; aggregate CDS coverage may hide which VEGFA isoform is affected.",
    "Important example where RDG should be isoform-aware, not only gene-total aware.",
    "Reporter constructs with VEGFA isoform contexts",
    "Bastide et al., Nucleic Acids Research, 2008",
    "https://pmc.ncbi.nlm.nih.gov/articles/PMC2367723/",
    "Treat VEGFA as an isoform-specific translation decision, not a simple CDS up/down gene."
  ),
  entry(
    "CDKN1A / p21",
    "Human",
    "Cell-cycle arrest, p53 response, senescence",
    "uORF in the CDKN1A 5-prime UTR",
    "Negatively regulates downstream p21 CDS translation",
    "Translation of the upstream ORF reduces initiation at the main ORF.",
    "Leader uORF footprints should anti-correlate with p21 CDS output when the uORF is engaged.",
    "Senescence marker where protein output may be post-transcriptionally dampened.",
    "Reporter assays",
    "Kim et al., Biochemical and Biophysical Research Communications, 2012",
    "https://pubmed.ncbi.nlm.nih.gov/22771799/",
    "Useful for interpreting p21/CDKN1A high mRNA but unexpectedly weak ribosome/CDS signal."
  ),
  entry(
    "CEBPB",
    "Mammal / human",
    "mTOR signaling, inflammation, differentiation, proliferation",
    "Conserved out-of-frame uORF near the LAP initiation site",
    "Changes isoform choice rather than only total CDS output",
    "uORF translation prevents initiation at LAP and promotes reinitiation at the downstream LIP start site; mTOR/eIF signaling shifts LAP:LIP balance.",
    "Ribosome initiation shifts among LAP*, LAP, and LIP start sites; gene-level CDS sums can miss the decision.",
    "Benchmark for RDGs with alternative in-CDS start nodes and isoform ratio outputs.",
    "Reporter assays, protein isoform analysis, Delta-uORF mouse model",
    "Calkhoven et al., Genes & Development, 2000; Wethmar et al., Genes & Development, 2010",
    "https://pmc.ncbi.nlm.nih.gov/articles/PMC2802187/",
    "CEBPB is in the ISR marker list; interpret as an isoform decision when possible."
  ),
  entry(
    "CEBPA",
    "Mammal / human",
    "Differentiation and proliferation control",
    "Conserved uORF influencing downstream alternative start-site use",
    "Changes long:short C/EBPalpha isoform ratio",
    "uORF-dependent reinitiation integrates eIF2/eIF4E signaling and controls initiation at downstream in-frame starts.",
    "Different initiation-site footprints within the CDS rather than a simple clean-CDS total shift.",
    "General isoform-decision benchmark for RDGs.",
    "Reporter and protein isoform assays",
    "Calkhoven et al., Genes & Development, 2000",
    "https://pubmed.ncbi.nlm.nih.gov/10921906/",
    "Relevant as a conceptual pair to CEBPB; not part of the current dominant-state marker table."
  ),
  entry(
    "AMD1 / AdoMetDC / SAMDC",
    "Mammal",
    "Polyamine homeostasis",
    "Very short MAGDIS peptide uORF near the cap",
    "High polyamines repress downstream AMD1 CDS; low polyamines permit CDS translation",
    "Polyamines increase uORF recognition and peptide-dependent ribosome stalling near termination, blocking access to the downstream CDS.",
    "High leader/uORF occupancy with lower AMD1 CDS translation under high polyamine conditions.",
    "Classic metabolite-sensing uORF and ribosome-stalling benchmark.",
    "Mutagenesis, in vitro translation, ribosome pausing/stalling assays",
    "Ivanov et al., Nucleic Acids Research, 2010; Mize and Morris, RNA, 2001",
    "https://pmc.ncbi.nlm.nih.gov/articles/PMC2811004/",
    "The polyamine system is a strong example where the uORF peptide itself is the sensor."
  ),
  entry(
    "CPA1",
    "Saccharomyces cerevisiae",
    "Arginine abundance",
    "Single uORF encoding the arginine attenuator peptide",
    "Arginine represses CPA1 CDS translation",
    "Arginine causes nascent-peptide-mediated ribosome stalling at the uORF termination codon, blocking scanning ribosomes and promoting NMD.",
    "Stalled ribosome footprint/toeprint near uORF stop; downstream CDS initiation reduced.",
    "Benchmark for metabolite-dependent uORF stalling distinct from ATF4 delayed reinitiation.",
    "Mutagenesis, cell-free translation, toeprinting, NMD assays",
    "Gaba et al., EMBO Journal, 2001; Gaba et al./CPA1 NMD studies, 2005",
    "https://pmc.ncbi.nlm.nih.gov/articles/PMC125715/",
    "Useful fungal comparison to separate scanning blockade from reinitiation delay."
  ),
  entry(
    "ARG2 / arginine attenuator peptide",
    "Neurospora crassa and fungi",
    "Arginine abundance",
    "Conserved uORF encoding a 24-residue arginine attenuator peptide",
    "Arginine represses downstream ARG2/arginine biosynthesis CDS translation",
    "Arginine triggers peptide-dependent ribosome stalling at the uORF stop codon and blocks downstream initiation.",
    "Toeprint/footprint enrichment at the uORF termination region with lower downstream CDS signal.",
    "Benchmark for conserved nascent-peptide stalling logic.",
    "Toeprinting, conserved peptide mutagenesis, cell-free translation",
    "Wang and Sachs, Mol Cell Biol, 1997; Spevak et al., Journal of Biological Chemistry, 2010",
    "https://pmc.ncbi.nlm.nih.gov/articles/PMC232343/",
    "Shows that uORF amino acid sequence, not just uAUG position, can encode regulation."
  ),
  entry(
    "HCMV UL4 / gpUL4",
    "Human cytomegalovirus in human cells",
    "Viral late-gene translational control",
    "22-codon uORF2 with terminal diproline motif",
    "Represses downstream gpUL4 translation and can buffer output when ribosome loading changes",
    "Nascent peptide blocks termination at the uORF stop codon, leaving a stalled ribosome barrier for scanning ribosomes.",
    "Strong ribosome stalling at uORF2 stop; downstream main ORF reduced or buffered.",
    "Best model for collision/stalling-based RDG edges.",
    "Mutational analysis, peptidyl-tRNA detection, ribosome stalling assays, quantitative reporters",
    "Alderete et al., Journal of Virology, 1999; Bottorff et al., PLOS Genetics, 2022",
    "https://pubmed.ncbi.nlm.nih.gov/10482583/",
    "Viral but highly informative for interpreting peptide-dependent stalls in human transcript leaders."
  ),
  entry(
    "THPO / thrombopoietin",
    "Human",
    "Platelet production; hereditary thrombocythemia",
    "Several inhibitory uORFs in the THPO 5-prime leader, especially uORF7",
    "Normal uORFs repress THPO CDS; disease mutations remove/restructure repression and increase THPO",
    "Overlapping or strong uORFs prevent efficient physiological start-site initiation; 5-prime UTR mutations disrupt this brake.",
    "Loss of leader uORF function should increase clean CDS translation and protein output.",
    "Disease benchmark for loss-of-uORF causing gain of protein expression.",
    "Human genetics, serum protein, 5-prime UTR reporter/mutagenesis",
    "Wiestner et al., Nature Genetics, 1998; Kondo et al., Blood, 1998; Ghilardi et al., Blood, 1998",
    "https://pubmed.ncbi.nlm.nih.gov/9425899/",
    "Gene symbol can be confused with thyroid peroxidase; here THPO means thrombopoietin."
  ),
  entry(
    "HR / U2HR",
    "Human",
    "Marie Unna hereditary hypotrichosis",
    "Inhibitory uORF in the HR 5-prime UTR",
    "Normal uORF represses HR CDS; uORF mutations increase HR translation",
    "Loss-of-function or missense changes in the inhibitory uORF release translation of the main HR ORF.",
    "Higher HR CDS/protein output when the uORF is disrupted.",
    "Human disease example where loss of repression, not loss of protein, is pathogenic.",
    "Family genetics plus functional reporter assays",
    "Ramot et al., Experimental Dermatology, 2010; Kim et al., Human Molecular Genetics, 2010",
    "https://pubmed.ncbi.nlm.nih.gov/20163456/",
    "U2HR denotes the regulatory upstream ORF, not an independent canonical protein-coding gene."
  ),
  entry(
    "CDKN1B / p27KIP1",
    "Human",
    "MEN4 / endocrine tumor predisposition",
    "Regulatory uORF in CDKN1B 5-prime UTR",
    "A pathogenic uORF deletion reduces p27 CDS translation",
    "The deletion lengthens the uORF peptide and shortens the intercistronic region, reducing reinitiation at the main CDKN1B start.",
    "Lower p27 CDS translation despite intact coding sequence.",
    "Disease benchmark for altered uORF length/spacing reducing tumor suppressor protein.",
    "Patient genetics, reporter assays, polysome profiling",
    "Occhi et al., PLOS Genetics, 2013",
    "https://pmc.ncbi.nlm.nih.gov/articles/PMC3605397/",
    "Good example where uORF mutation does not simply destroy a start codon; it changes reinitiation geometry."
  ),
  entry(
    "CDKN2A / p16INK4A",
    "Human",
    "Familial melanoma predisposition",
    "5-prime UTR mutations create aberrant upstream initiation/uORF events",
    "Created uORFs reduce p16 main ORF translation",
    "New upstream initiation diverts scanning ribosomes away from the tumor suppressor CDS.",
    "Reduced p16 reporter/protein output from alleles with newly created upstream starts.",
    "Disease benchmark for gain-of-uORF causing loss of tumor suppressor expression.",
    "Familial genetics and functional translation assays",
    "Liu et al., Nature Genetics, 1999",
    "https://www.nature.com/articles/ng0199_128",
    "Also summarized in human uORF-disease reviews."
  ),
  entry(
    "BACE1",
    "Human",
    "Alzheimer disease biology; neuronal stress",
    "Multiple upstream AUGs/uORFs in a long GC-rich 5-prime UTR",
    "uAUG/uORFs strongly inhibit BACE1 translation in several assays; stress-dependent derepression is debated",
    "Upstream starts divert scanning ribosomes; alternative splicing and leader structure modulate access to the BACE1 start.",
    "Leader footprints and altered CDS translation without proportional mRNA change, especially under stress contexts.",
    "Relevant example where uORFs, structure, and stress all interact; not a clean single-uORF model.",
    "5-prime UTR reporter assays, in vitro translation, cell-type comparisons",
    "Mihailovich et al., Nucleic Acids Research, 2007; De Pietri Tonelli et al., Molecular Biology of the Cell, 2004",
    "https://pmc.ncbi.nlm.nih.gov/articles/PMC1888809/",
    "Use with caveat: multiple publications disagree on how much uORFs mediate stress-dependent BACE1 induction."
  ),
  entry(
    "MDM2",
    "Human and mouse",
    "p53 pathway and oncogene expression",
    "Two uORFs in the long MDM2 transcript leader",
    "Both uORFs repress MDM2 translation; uORF1 is much stronger",
    "uORF1 has sequence-specific inhibitory properties; removing both uORFs strongly increases translation efficiency.",
    "Leader uORF engagement should lower downstream MDM2 CDS output.",
    "p53-feedback RDG candidate, especially in GENE/CONDITION branches involving TP53 perturbation.",
    "uORF deletion, order/context swaps, reporter assays",
    "Jin et al., Journal of Biological Chemistry, 2003",
    "https://pubmed.ncbi.nlm.nih.gov/12730202/",
    "Useful for distinguishing peptide-sequence effects from simple uAUG occupancy."
  ),
  entry(
    "SOCS1",
    "Human",
    "JAK/STAT and interferon feedback",
    "uORF in an upstream exon/5-prime leader",
    "Represses SOCS1 main ORF translation",
    "The upstream ORF ends just before the major ORF and reduces translation of the downstream protein.",
    "Leader translation with lower SOCS1 CDS protein output.",
    "Interferon pathway feedback gene; useful candidate if future RDGs include SOCS genes.",
    "Promoter/5-prime leader luciferase constructs and uORF start mutation",
    "Schlueter et al., Biochemical and Biophysical Research Communications, 2000",
    "https://pubmed.ncbi.nlm.nih.gov/10679190/",
    "SOCS1 is interferon-induced transcriptionally, so uORF effects may modulate rather than define total abundance."
  ),
  entry(
    "Tyrosine kinases / MET / KDR",
    "Human",
    "Cancer signaling and proto-oncogene dosage",
    "Frequent uORFs in tyrosine kinase transcript leaders; naturally occurring loss-of-uORF alleles in MET and KDR",
    "uORFs generally repress kinase CDS translation; loss-of-uORF can increase proto-oncogene output",
    "Upstream initiation limits scanning access to kinase CDS starts; disrupting uORF starts derepresses translation.",
    "Higher kinase CDS translation when leader uORF starts are removed or mutated.",
    "Broad cancer RDG candidate class; prioritizes oncogenes with leader uORF losses.",
    "Systematic reporter ablation and variant analysis",
    "Wethmar et al., Oncogene, 2015",
    "https://pmc.ncbi.nlm.nih.gov/articles/PMC4820681/",
    "This is a family-level result, not one single transcript mechanism."
  ),
  entry(
    "MYCN / MYCNOT",
    "Human neuroblastoma cells",
    "MYCN alternative exon 1b splicing",
    "uORF in MYCN/MYCNDelta1b leader; MYCNOT translated from the MYCNDelta1b upstream AUG",
    "The uORF positively affects MYCN translation from full-length MYCN mRNA but not MYCNDelta1b mRNA",
    "Alternative splicing changes whether the upstream AUG produces MYCNOT and how it affects MYCN CDS translation.",
    "Isoform-specific leader and CDS footprints; full-length and Delta1b transcripts should be separated.",
    "Important naming caution for MYC-family RDGs.",
    "Plasmid translation assays, uAUG mutagenesis, antibody evidence for MYCNOT",
    "Besancon et al., BMC Cancer, 2009",
    "https://pmc.ncbi.nlm.nih.gov/articles/PMC2810302/",
    "MYCNOT is MYCN Overlap Transcript. It is not the same as c-MYC/MYC predicted uoORFs in our current RiboCrypt MYC transcript."
  ),
  entry(
    "MYC P0 / MYCHEX1",
    "Human",
    "c-MYC alternative promoter P0 transcript",
    "P0 tricistronic mRNA with ORF1, MYCHEX1, and c-Myc1/c-Myc2 translation controlled by IRES elements",
    "Not a simple repressive uORF; produces additional ORF products and c-MYC isoforms",
    "Internal ribosome entry sites promote cap-independent translation of MYCHEX1 and c-Myc ORFs from the same transcript.",
    "Multiple translated ORFs in one c-MYC transcript; aggregate gene-level CDS can miss upstream ORF products.",
    "Cautionary reference for comparing predicted MYC uoORFs against known c-MYC upstream ORFs.",
    "Bicistronic/tricistronic reporter assays and IRES mapping",
    "Nanbru et al., Oncogene, 2001",
    "https://www.nature.com/articles/1204548",
    "Before claiming novelty for MYC RDG edges, map predicted uoORFs to MYCHEX1/ORF1 and transcript promoter context."
  ),
  entry(
    "CPT1C",
    "Human",
    "Energy availability, glucose deprivation, palmitate, AMPK",
    "Single repressive uORF in the CPT1C 5-prime UTR",
    "CDS repressed basally; repression is relieved by selected metabolic stresses",
    "The uORF suppresses main ORF initiation; cellular energy signals modulate this repression.",
    "Energy-stress branches should show increased clean CDS translation relative to uORF engagement.",
    "Metabolism/stress RDG benchmark outside the ISR core.",
    "5-prime UTR reporter assays and stress treatments",
    "Hughes et al., PLOS ONE, 2011",
    "https://pubmed.ncbi.nlm.nih.gov/21961029/",
    "Useful conceptual link between nutrient state and leader-mediated translation decisions."
  ),
  entry(
    "CFTR",
    "Human",
    "CFTR-related disease and bronchiectasis",
    "Native 5-prime UTR uORF plus a disease-associated c.-34C>T-created overlapping uORF",
    "uORF and RNA structure keep CFTR expression low; c.-34C>T strongly decreases expression",
    "Created upstream AUG forms an overlapping out-of-frame uORF, reducing translation efficiency and mRNA stability.",
    "Variant allele should show leader/upstream translation and strongly reduced CFTR CDS output.",
    "Disease benchmark for newly created overlapping uoORFs reducing normal protein expression.",
    "Patient variant, luciferase reporters, mRNA stability and translation assays",
    "Lukowski et al., Human Mutation, 2011; Lukowski et al., Human Molecular Genetics, 2015",
    "https://pubmed.ncbi.nlm.nih.gov/21837768/",
    "Shows why overlapping uORFs need to be excluded from clean-CDS quantification."
  )
))

known_uorf_effects <- known_uorf_effects[order(known_uorf_effects$gene_or_element), ]

analysis_dir <- if (dir.exists("dominant_cell_states")) "dominant_cell_states" else "."
results_dir <- Sys.getenv(
  "DOMINANT_CELL_STATES_RESULTS_DIR",
  unset = file.path(analysis_dir, "results")
)
out_dir <- file.path(results_dir, "curated_inputs")
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
out_file <- file.path(out_dir, "known_uorf_effects_with_citations.csv")
write.csv(known_uorf_effects, out_file, row.names = FALSE, na = "")
message("Wrote ", out_file, " with ", nrow(known_uorf_effects), " rows.")
